---
#define the host IP and the OS
ansible_host: 192.168.10.13
ansible_network_os: ios

#interfaces IP configuration
interfaces:
 - name: ethernet 0/1
   description: Connect to PE01
   ipv4: 10.10.103.1 255.255.255.0
 - name: ethernet 0/2
   description: Connect to PE02
   ipv4: 10.10.203.1 255.255.255.0
 - name: loopback 0
   description: Loopback of P03
   ipv4: 3.3.3.3 255.255.255.255

#OSPF process definition and area configuration
ospf_process: 1
ospf_area: 0